credentials:
  usernames:
    admin:
      name: Admin User
      password: 'admin123'
    viewer:
      name: View Only
      password: 'viewer123'
cookie:
  name: 'dashboard'
  key: 'abcdef'
  expiry_days: 30
